name: CI/CD test

on:
  push:
    branches: [CICD]

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > piottoArq-key.pem && chmod 600 piottoArq-key.pem
          cat piottoArq-key.pem 
          echo ${USER_NAME}@${HOSTNAME}
