name: CI/CD test

on:
  push:
    branches: [CICD]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME: ${{ secrets.HOSTNAME  }}
          USER_NAME: ${{ secrets.USERNAME  }}

        run: |
          ssh -i "${PRIVATE_KEY}" "${USER_NAME}@${HOSTNAME}"

            cd /home/ubuntu/CICD-test &&
            touch xablau.txt
