name: CI/CD test

on:
  push:
    branches: [CICD]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Access to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOSTNAME}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: whoami
